default: &default
  adapter: mysql2
  encoding: utf8
  database: temp_test
  username: root
  password:
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  ssl_mode: :disabled
  sslverify: false

development:
  <<: *default

int:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

test:
  <<: *default
  database: temp_test_test
